#ifndef _UNIFORM_EXTRA_VECTOR_CONSTANTS_H
#define _UNIFORM_EXTRA_VECTOR_CONSTANTS_H

#include "uniformMacro.h"

#ifdef MCPE_PLATFORM_NX
layout(binding = 1) uniform SfxConstants {
#endif
// BEGIN_UNIFORM_BLOCK(SfxConstants) - unfortunately this macro does not work on old Amazon platforms so using above 3 lines instead
UNIFORM vec4 EXTRA_VECTOR1;
UNIFORM vec4 EXTRA_VECTOR2;
UNIFORM vec4 EXTRA_VECTOR3;
UNIFORM vec4 EXTRA_VECTOR4;
UNIFORM vec4 EXTRA_VECTOR5;
UNIFORM vec4 EXTRA_VECTOR6;
UNIFORM vec4 EXTRA_VECTOR7;
UNIFORM vec4 EXTRA_VECTOR8;
UNIFORM vec4 EXTRA_VECTOR9;
UNIFORM vec4 EXTRA_VECTOR10;
UNIFORM vec4 EXTRA_VECTOR11;
UNIFORM vec4 EXTRA_VECTOR12;
UNIFORM vec4 EXTRA_VECTOR13;
UNIFORM vec4 EXTRA_VECTOR14;
UNIFORM vec4 EXTRA_VECTOR15;
UNIFORM vec4 EXTRA_VECTOR16;
UNIFORM vec4 NTES_PBR_ENTITY_SHADOW_MATRIX0;
UNIFORM vec4 NTES_PBR_ENTITY_SHADOW_MATRIX1;
UNIFORM vec4 NTES_PBR_ENTITY_SHADOW_MATRIX2;
UNIFORM vec4 NTES_PBR_ENTITY_SHADOW_MATRIX3;
UNIFORM vec4 NTES_PBR_ENTITY_SHADOW_PARAMS;
UNIFORM vec4 NTES_PBR_ENTITY_SHADOW_PARAMS2;
UNIFORM vec4 MATERIAL_INSTANCE_PARAM1;
UNIFORM vec4 MATERIAL_INSTANCE_PARAM2;
UNIFORM vec4 MATERIAL_INSTANCE_PARAM3;
UNIFORM vec4 MATERIAL_INSTANCE_PARAM4;
UNIFORM vec4 SUN_DIR;
UNIFORM vec4 WATER_TEXTURE_UV_RANGE;
UNIFORM vec4 SKY_NEAR_COLOR;
UNIFORM vec4 SKY_FAR_COLOR;
UNIFORM vec4 RAIN_NEAR_COLOR;
UNIFORM vec4 RAIN_FAR_COLOR;
UNIFORM vec4 COLOR_MAPPING_PARAM;
END_UNIFORM_BLOCK

#endif
